name: date_cupertino_bottom_sheet_picker
description: "This is a date package in the form of Cupertino and you can set the age limit of your users."
version: 0.0.5
homepage: "https://github.com/SwanFlutter/date_cupertino_bottom_sheet_picker.git"

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.0
  shamsi_date: ^1.0.4
  fade_animation_delayed: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

