name: date_cupertino_bottom_sheet_picker
description: "This is a date package in the form of Cupertino and you can set the age limit of your users."
version: 0.0.3+1
homepage: "https://github.com/SwanFlutter/date_cupertino_bottom_sheet_picker.git"

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

